### ISSUE TITLE
Questions: tree sitter, git, ollama

### ISSUE THREAD

**Issue by magaton** [OpenBMB/RepoAgent#60]
Hello, interesting project and architecture.
I see that the support for other programming languages is left for future. Have you considered using tree-sitter for code parsing?

Also, why did you decide to use pre-commit hooks instead of pullling git repository with a scheduler. Llama index github reader could be leveraged in that case.

Do you plan to support Ollama and if so, which of the open source models you reckon would be the best fit?

Thanks

**Comment by magaton** [comment]
Anyone?

**Comment by Umpire2018** [comment]
>  I see that the support for other programming languages is left for future. Have you considered using tree-sitter for code parsing?

Hi there! Thank you for your suggestion. I will look into it. It would be great if you can share any details with me.

**Comment by Umpire2018** [comment]
![image](https://github.com/OpenBMB/RepoAgent/assets/138990495/da605cf3-a84b-4cbd-be40-26420774b59a)

Reference: [here](http://arxiv.org/abs/2402.16667)

We applied
1.  [Abstract Syntax Tree (AST)](https://docs.python.org/3/library/ast.html) to extract all Classes and Functions within the file, including their type, name, code snippets, etc which is similar with 

> [Tree-sitter](https://github.com/tree-sitter/tree-sitter) is a parser generator tool and an incremental parsing library. It can build a concrete syntax tree for a source file and efficiently update the syntax tree as the source file is edited).

![image](https://github.com/OpenBMB/RepoAgent/assets/138990495/c33165fb-6cc6-4e5c-9fd1-3dbbba966f5b)
<img width="524" alt="image" src="https://github.com/OpenBMB/RepoAgent/assets/138990495/e3bb14c3-c041-4441-ac65-a88254fe8034">

2. [Jedi](https://github.com/davidhalter/jedi) to find_all_referencer of single function in `repo_agent/doc_meta_info.py Line 270` .

Seems like tree-sitter is better than ast because it provides multiple programming language support.
<img width="152" alt="image" src="https://github.com/OpenBMB/RepoAgent/assets/138990495/bc2fcc40-d1d0-47c6-80c3-e218f9087c7d">

Correct me if i am wrong. @LOGIC-10

**Comment by magaton** [comment]
Thanks for the response guys. Again, excellent work. I am on the same boat and the support for the multiple programming languages is a stopper from using your project.

As I can see you do Python AST + Jedi for the function calls.
Replacing python AST with tree-sitter could bring you closer to multi-lnaguage support , but Jedi is usable only for python. 

AST is only one layer and here with Jedi you want to add function calls into the picture.

But, there is a standard notion for extracting codebase semantics. It is called [CPG](https://cpg.joern.io/) (code property graph)
and a reference implementation called [Joern](https://docs.joern.io/):

Have you maybe considered that?

**Comment by Umpire2018** [comment]
> AST is only one layer and here with Jedi you want to add function calls into the picture.
> 
> But, there is a standard notion for extracting codebase semantics. It is called [CPG](https://cpg.joern.io/) (code property graph) and a reference implementation called [Joern](https://docs.joern.io/):

I wonder if [CPG](https://blog.llvm.org/posts/2021-02-23-llvm-meets-code-property-graphs/) have a python implementation? https://github.com/markgacoka/codepropertygraph may not be a good choice.

And the goal is to replace AST + Jedi via one or multiple library in order to acheieve multi-language support.

**Comment by magaton** [comment]
I am using Joern for CPG -> Neo4j, but that is scala
There is also https://pypi.org/project/cpggen/ in python

**Comment by Umpire2018** [comment]
> AppThreat/cpggen: This repository has been archived by the owner on Jan 8, 2024. It is now read-only.

It seems that now is not a good time to introduce CPG but we will definitely consider tree sitter.

**Comment by magaton** [comment]
Understood, but when you use tree-sitter, maybe you can only take its CST output and use a code chunker from llama index
https://docs.sweep.dev/blogs/chunking-improvements

**Comment by Umpire2018** [comment]
> Do you plan to support Ollama and if so, which of the open source models you reckon would be the best fit?

Seems like `Ollama` have provided [openai-compatibility](https://ollama.com/blog/openai-compatibility) so i think support Ollama or others open source llm is not high priority.

Right now we only used `Chat completions` ablility.

Similar projects for reference are as follows:
1. [vllm](https://github.com/vllm-project/vllm)
2. [llama-cpp-python](https://github.com/abetlen/llama-cpp-python)
3. [Ollama](https://github.com/ollama/ollama/blob/main/docs/openai.md)

**Comment by Major-wagh** [comment]
Hello, I too wanted support for languages other then python. Does anybody know the approach or neccsessary changes to be done to the existing code repository?

**Comment by biandan** [comment]
openai很多地方无法使用，我也期待支持ollama

**Comment by sandeshchand** [comment]
is there any method for supporting multiple programming langauge ?

**Comment by alikinir** [comment]
also interested in more languages to be supported. ( typed script + scala )
